# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fcf41f0f3c3c72ca3e21667ab2d5ff66a3a1dce6d3f780d4fa110e56deab453199e2d39e3511461165303f96dce03846587415dfe762d75ba6d7367f6a17d7d

test:
  secret_key_base: 628482c07f848a86b456b1b04b8ff13ce80b5597a25155a0d4a24a2e64f1bf87d090a8b80d037b896bfe6003eac4b9c0d15e783b4355f6842ae56d1ecc749a79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
